### ISSUE TITLE
Expression function "contains" array example does not work

### ISSUE THREAD

**Issue by averikitsch** [github/docs#10239]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#contains

### What part(s) of the article would you like to see updated?

Currently the "Example using an array" for contains does not work as intended.
```
Example using an array
contains(github.event.issue.labels.*.name, 'bug')
```
To work I've updated it to 
```
contains(join(github.event.issue.labels.*.name, ', '),'bug')
```

My example:
```
on:
  pull_request:
    types: [labeled, unlabeled]


jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo ${{contains(join(github.event.pull_request.labels.*.name, ', '),'needs')}}
          echo ${{contains(github.event.pull_request.labels.*.name,'needs')}}
```

When I add the label "needs work", I see the print out
```
true
false
```
