### ISSUE TITLE
Github Actions YAML python-version example should use strings, not floats

### ISSUE THREAD

**Issue by alexkyllo** [github/docs#11019]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Building and testing Python](https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python?langId=py)

### What part(s) of the article would you like to see updated?

The python-version example should use strings and not floats.
```yaml
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
```
should be
```yaml
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
```

Why? Because Python 3.10 is out, and if it's specified as a float, it gets interpreted as 3.1. Using strings instead of floats in the docs will help many users avoid this pitfall.
