### ISSUE TITLE
OIDC w/ AWS example doesn't appear to be valid JSON

### ISSUE THREAD

**Issue by Hollywood** [github/docs#11534]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Configuring OpenID Connect in Amazon Web Services](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services)

### What part(s) of the article would you like to see updated?

The last line in the code block on lines 44 - 47 does not look like valid json:

```yaml{:copy}
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "https://github.com/octo-org",
    "token.actions.githubusercontent.com:sub": "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
```
Was it meant to be?

```yaml{:copy}
"Condition": {
  "StringEquals": {
    "token.actions.githubusercontent.com:aud": "https://github.com/octo-org",
    "token.actions.githubusercontent.com:sub": "repo:octo-org/octo-repo:ref:refs/heads/octo-branch"
```
