### ISSUE TITLE
Listed limitations of reusable workflows incomplete

### ISSUE THREAD

**Issue by cmitz** [github/docs#11830]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#limitations

### What part(s) of the article would you like to see updated?

I would like to have this limitation included:

> * Reusable workflows do not support the `strategy` property.

That is because I tried using a reusable workflow with that property but GitHub Actions errored with this error:
> The workflow is not valid. .github/workflows/deploy_release.yml (Line: 22, Col: 5): Unexpected value 'strategy' .github/workflows/deploy_release.yml (Line: 31, Col: 21): Unrecognized named-value: 'matrix'. Located at position 1 within expression: matrix.package_type

### Additional information

![afbeelding](https://user-images.githubusercontent.com/5594436/141119970-3636e3c4-a2f8-4ccb-850c-4d8d2e30067d.png)

**Comment by skedwards88** [comment]
🤔 I wasn't able to reproduce this. e.g. something like this worked for me (https://github.com/ske-test-org/test-org-repo/actions/runs/1518627718):

```
name: Reusable workflow example

on:
  workflow_call:

jobs:
  example_job:
    name: Print input and secrets to STDOUT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
      - name: Print
        run: echo "done"
```

Since it looks like the docs don't need to be updated, I am going to close out this issue and PR. Please comment with more details about the failure you observe (e.g. link to a public workflow run log) if you think the docs still need an update! For troubleshooting, [GitHub Support Community](https://github.community/) might be a better place to post.

Even though we didn't accept this contribution, I hope to see more from you in the future! I especially liked that you included the error message in your issue--that type of context helps a ton!

**Comment by cmitz** [comment]
@skedwards88 Thank you for taking the time to look at this and creating the counterexample. However, the issue will still persist if you add the `strategy` to the **caller workflow**, like this:

```yaml
name: Call a reusable workflow

on:
 push:
 workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ske-test-org/test-org-repo/.github/workflows/called.yml@main
    strategy:
      matrix:
        node: [10, 12, 14]
```

I've made an example repository+action run here: https://github.com/cmitz/actions-test-organization/actions/runs/1519814069
