### ISSUE TITLE
The documentation suggests an invalid value for the name of a secret

### ISSUE THREAD

**Issue by lpmi-13** [github/docs#12094]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The article contains the following example configuration:

```
steps:
  - name: My first action
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIRST_NAME: Mona
      LAST_NAME: Octocat
```

However, when attempting to follow this example, I was presented with an error in the UI as follows:

"Failed to add secret. Secret names must not start with GITHUB_."

If this is not a valid naming convention for secrets, then it shouldn't be used in the documentation.

### Additional information

![error when attempting to create a secret](https://user-images.githubusercontent.com/5070516/142296142-7b2cf448-9313-4d21-9b54-20ee87ca99b5.png)
