### ISSUE TITLE
Document `workflow_run` behaviour when workflow name contains special characters

### ISSUE THREAD

**Issue by starizard** [github/docs#12572]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run

### What changes are you suggesting?
[possible bug]
workflows triggered by `workflow_run` do not work if the workflow name contains characters like `[ ]`

for example:
```
name: "[foo] parent"
on:
  push:
    branches:
      - "main"
    paths:
      - cloud/**
.
.
.
```
this parent workflow should trigger the child workflow

```
name: "[bar] child"
on:
  workflow_run:
    workflows:
      - "[foo] parent"
    branches:
      - main
    types:
      - completed
.
.
.
 ```
but it doesn't trigger the child workflow,

removing `[foo]` from the workflow name makes it work

**Comment by ramyaparimi** [comment]
@starizard 
Thanks so much for opening a PR! I'll get this triaged for review :zap:

**Comment by nikordaris** [comment]
are there any other special characters to avoid? Also, is the solution to just not use those special characters in your workflow names?

**Comment by lucascosti** [comment]
Hi @starizard, thanks for reporting this. I'm not totally sure if this is a bug or not, so before we update the docs, I've asked the Actions engineering team to clarify. Stay tuned.

**Comment by lucascosti** [comment]
Hi @starizard, I've checked with the engineering team, and I can confirm that this is a known bug.

As a workaround until this issue is fixed, you can escape the square brackets in the `workflow_run` workflow and it should work. For example:

```yaml
on:
  workflow_run:
    workflows: \[foo\] parent
```

I've tried a few other special characters, and they don't seem to be affected by this bug.

We don't document bugs in our documentation, so I'll close this docs issue.

For anyone else experiencing problems with this, please contact the [GitHub Support Community] or (https://github.community/) [GitHub Support](https://support.github.com/contact) 🙂.
