### ISSUE TITLE
encrypted secrets truncating newlines upon creation ( maybe only sometimes)

### ISSUE THREAD

**Issue by Gornoka** [github/docs#14207]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/security-guides/encrypted-secrets

### What part(s) of the article would you like to see updated?

Specify that action secrets can not be multiline strings, in the docs or change the behaviour. 

### Additional information

A week ago i was able to create a multiline encrypted secret on my machine, now when i try to create a secret containing multiple lines ( on a diferent machine) it does not work ( it removes all newlines ). It should  behave the same way on both machines and if the secret creation process truncates anything from the secret there should be a warning or at least a note in the docs. 

Machine 1 was running windows 10
Machine 2 was running windows 11 
Both use Chrome

**Comment by ramyaparimi** [comment]
@Gornoka 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by Johnpecker** [comment]
Coding

**Comment by AdorkableMJ** [comment]
> ### Code of Conduct
> 
> - [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)
> 
> ### What article on docs.github.com is affected?
> 
> https://docs.github.com/en/actions/security-guides/encrypted-secrets
> 
> ### What part(s) of the article would you like to see updated?
> 
> Specify that action secrets can not be multiline strings, in the docs or change the behaviour. 
> 
> ### Additional information
> 
> A week ago i was able to create a multiline encrypted secret on my machine, now when i try to create a secret containing multiple lines ( on a diferent machine) it does not work ( it removes all newlines ). It should  behave the same way on both machines and if the secret creation process truncates anything from the secret there should be a warning or at least a note in the docs. 
> 
> Machine 1 was running windows 10
> Machine 2 was running windows 11 
> Both use Chrome

I have some questions about some encrypted or coded or ciphered message recently and I'm trying to figure out what I need to do to decode it. ![IMG_20220119_093801.jpg](https://user-images.githubusercontent.com/98030204/150428020-d4307d93-47de-4b3f-8887-51490b78d0a0.jpg)![Screenshot_2022-01-19-09-40-53-327~2.jpg](https://user-images.githubusercontent.com/98030204/150427997-12db5137-74b3-48b7-9bba-0bc718053108.jpg). If anyone has any information to offer me on where it came from, what the message is, or how can figure it out, please advise

**Comment by Abhi9737** [comment]
Johnpecker 6 day's ago 
Coding

**Comment by AdorkableMJ** [comment]
So maybe I could learn something from those coded messages to be able to learn what they are by starting a pull request or by starting a project?

**Comment by Gornoka** [comment]
> So maybe I could learn something from those coded messages to be able to learn what they are by starting a pull request or by starting a project?

Assuming you are not a troll,
This is related to github actions, something that you will not need for now, if you want to learn about this topic now I would recommend you to checkout the quickstart guide for actions.

https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions

**Comment by AdorkableMJ** [comment]
I'm not a troll, I am a newby

**Comment by momo13302** [comment]
mercie pour tout les message

**Comment by momo13302** [comment]
thank you for all the messages

**Comment by AdorkableMJ** [comment]
I have identified the source of every reason any of my own accounts were
ever compromised in the manner in which they were... Now what's the
appropriate manner in which to either raise the issue or create a product
or project to help others like me in my situation...

My Google search question was "what to do about a developer of an app or
game lies about the retention of money and does not pay you for something
you legally did without any lawsuits... And Google being family friendly...
I don't see this as a family friendly thing to suggest as did I mean to
ask... Please advise

**Comment by ethomson** [comment]
Hi @Gornoka - thanks for opening this issue.  We should persist newlines in secrets on all platforms; can you provide some more information on how to reproduce this problem?

**Comment by Gornoka** [comment]
## Error and Action

Thanks for your Answer @ethomson , sorry for my late reply.
I have reproduced this issue just now on my machine. 
## Steps to reproduce
1. created new private repository
2. added test action that reads ssh key, writes it to file, then tries to add it to the ssh deamon
3.  observe failure with ````Error loading key "ssh_key_file": invalid format ````
  *  see test action below
````yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          TEST_DEPLOY_KEY: ${{secrets.TEST_DEPLOY_KEY}}
        run: |
          # give access to the private repos
          ## add deploy key for webapp academy
          touch ssh_key_file
          echo $TEST_DEPLOY_KEY > ssh_key_file
          echo "#### echo key"
          echo $IAIA_WEBAPP_DEPLOY_KEY
          echo "**** add key"
          sudo chmod 600 ssh_key_file
          eval "$(ssh-agent -s)"
          echo "~~~~ grep + wc key file filtered"
          grep 'SSH' ssh_key_file | wc
          echo "---- wc key file"
          wc ssh_key_file
          echo "%%%% wc env var directly"
          echo $TEST_DEPLOY_KEY | wc
          echo "////"
          ssh-add ssh_key_file
          # test deploy key
          ssh  -tvv git@github.com & sleep .1
````

  * output 
````shell
shell: /usr/bin/bash -e {0}
  env:
    TEST_DEPLOY_KEY: ***
#### echo key

**** add key
Agent pid 1564
~~~~ grep + wc key file filtered
      1      44    26
---- wc key file
   1   44 [26]
ssh_key_file
%%%% wc env var directly
      1      44    2622
////
Error loading key "ssh_key_file": invalid format
Error: Process completed with exit code 1.
````
# Additional information
## Misc
* copying of the ssh key was done from windows terminal, the copy operation worked when pasting it into notepad++
![image](https://user-images.githubusercontent.com/45569834/152761855-9c4fca2b-1bbd-44e9-82c8-f4c50a984171.png)
* The copy operation yielded windows newlines.
* current workaround with gpg to encrypt ssh keys is not practical in our org, since we have a repo that needs to clone ~10 private repos, during actions and also has some bots running on it, which would require 40++ ssh keys encrypted ssh keys in the repo, plus the debugging/ maintenacne process of that is a nightmare.
* Windows version is german, ( if you need any of the outputs translated or something else don't hesistate to ask)
* the above script works, in another repo, where the key has been created in late December./ early January

## Browser
Chrome version : 97.0.4692.99 (Offizieller Build) (64-Bit)

## OS
Edition	Windows 11 Pro
Version	21H2
Installiert am	‎05.‎11.‎2021
Betriebssystembuild	22000.438
Leistung	Windows Feature Experience Pack 1000.22000.438.0

## Device
Gerätename	~~~~~~~~~~~~~
Prozessor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installierter RAM	32,0 GB (31,7 GB verwendbar)
Geräte-ID	~~~~~~~-~~~~-~~~~-~~~~-~~~~
Produkt-ID	#####-#####-#####-#####
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

## OS
Edition	Windows 11 Pro
Version	21H2
Installiert am	‎05.‎11.‎2021
Betriebssystembuild	22000.438
Leistung	Windows Feature Experience Pack 1000.22000.438.0

##
If you need any additional Information or have a fix to try please let me know.

with kind regards
Lukas
