### ISSUE TITLE
Local references to reusable workflows don't work for private repos

### ISSUE THREAD

**Issue by robwruck** [github/docs#14649]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

### What part(s) of the article would you like to see updated?

It is stated that
```
You reference reusable workflow files using one of the following syntaxes:
- {owner}/{repo}/{path}/{filename}@{ref} for reusable workflows in public repositories.
- ./{path}/{filename} for reusable workflows in the same repository.
```

The second syntax, however, does not work for private repos. If you try it, you get a misleading error message:

```
The workflow is not valid. ./.github/workflows/reusable.yml: Expected document start parse event Unexpected type '' encountered while reading 'root'. The type 'MappingToken' was expected.
```

The exact same file works in a public repo.
Please add a note about that.

**Comment by ramyaparimi** [comment]
@robwruck 
Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by ethomson** [comment]
Hi @robwruck - reusable workflows in private repositories should be able to be referenced that way; this workflow (in a private repository) succeeds for me: 

```yaml
name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/reusable.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
```

Can you provide a workflow that isn't working?  🤔
