### ISSUE TITLE
Quote language versions in YAML examples

### ISSUE THREAD

**Issue by skedwards88** [github/docs#14764]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

YAML examples in https://docs.github.com/actions

### What part(s) of the article would you like to see updated?

YAML treats floats like `2.10` as `2.1`. This can lead to workflows using a different language version than intended. We should update the YAML examples to quote language versions to avoid this. To help users who copy-paste-modify without understanding the nuance, we should quote all language versions, even ones that would not be affected by this parsing.

For example:

```
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
```

should be changed to 

```
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
```

Then if a user copies the example but wants to include version 3.10, they can easily plug in the new value without knowing they need to add quotes.

## Actions articles with examples that need quotes

- [ ] [Building and testing Node.js](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs)
- [ ] [Building and testing Ruby](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby)
- [ ] [Complete example for GitHub Actions](https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-circleci-to-github-actions#complete-example-for-github-actions)
- [ ] [GitHub Actions syntax for a matrix](https://docs.github.com/en/actions/migrating-to-github-actions/manually-migrating-to-github-actions/migrating-from-travis-ci-to-github-actions#github-actions-syntax-for-a-matrix)
- [ ] [Example: Using contexts to create matrices](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-contexts-to-create-matrices)
