### ISSUE TITLE
GITHUB_REF and GITHUB_REF_NAME examples in Actions docs unclear

### ISSUE THREAD

**Issue by oofnikj** [github/docs#15319]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

### What part(s) of the article would you like to see updated?

`GITHUB_REF` and `GITHUB_REF_NAME` show example values of `refs/heads/feature-branch-1` and `feature-branch-1` respectively. However this is inconsistent with the values populated in the case of a PR-triggered workflow. 

Given the description and example, one would expect to see the branch that triggered the workflow when running a PR-triggered workflow. Instead these variables are populated by values like `refs/pull/26/merge` and `26/merge` respectively. The variable that contains the desired data in this case is actually `GITHUB_HEAD_REF`.

The documentation should be updated to more accurately describe the content of GitHub Actions predefined variables.

**Comment by ramyaparimi** [comment]
@oofnikj Thanks so much for opening an issue! I'll triage this for the team to take a look :eyes:

**Comment by skedwards88** [comment]
Thanks for opening this issue! You proposal to add/clarify this information sounds good. You or anyone else is welcome to open a PR to address this. (Note that this was partially addressed in https://github.com/github/docs/pull/15304)

**Comment by Princeprince559** [comment]
What's next... 411 please

**Comment by wickkidd** [comment]
Why should `GITHUB_REF_NAME` be different for a PR? If it's supposed to return the source branch (a very useful thing) then it should do so regardless of the context. To me this seems more like a bug than bad documentation.

**Comment by Kurt-von-Laven** [comment]
It would certainly be more helpful for our use case to have a simpler way to get the branch name regardless of context.

**Comment by cmwilson21** [comment]
I think this has been covered and updated in a previous PR. I'm going to go ahead and close this now 💛

**Comment by airtonix** [comment]
@cmwilson21 in what PR?

**Comment by cmwilson21** [comment]
@airtonix Sorry, I may have been mistaken. I thought it was covered [here](https://github.com/github/docs/commit/16650c68293e9bdf652e4b10839d4206683abd6b). I'll reopen the issue.

My apologies! 🙈

**Comment by japui-coder** [comment]
GITHUB_REF and GITHUB_REF_NAME examples in Actions docs unclear #15319 #21932

**Comment by rlespinasse** [comment]
> Disclaimer: I'm the author of the following action

In this action https://github.com/rlespinasse/github-slug-action, the behavior, described by @wickkidd, is possible with `${{ env.GITHUB_REF_NAME }}` ([read more](https://github.com/rlespinasse/github-slug-action#github_ref_name)).

```yaml
- name: Inject slug/short variables
  uses: rlespinasse/github-slug-action@v4
  
- run:|
    echo "$GITHUB_REF_NAME will serve the internal behavior of GitHub Action"
    echo "${{ env.GITHUB_REF_NAME }} will serve the behavior of the GitHub Slug action"
  shell: bash
```

**Comment by walkerk1980** [comment]
This would be extremely useful to my team as we currently have to maintain hardcoded environment and terraform workspace names in our workflows, this forces us to have a different workflow for each environment. We could create some custom logic that only run on a Push or PR to export ref_name when event_name == push and github_base_ref when event_name == workflow_dispatch. I would highly prefer there to be some way to consistently get the ref_name regardless of event_name.


``` 
  terraform:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    env:
      working-directory: terraform
      TF_WORKSPACE: ${{ github.ref_name }}
      ARM_USE_OIDC: true
  ```

**Comment by danielricecodes** [comment]
Can you please just add `${{ github.branch_name }}`.  Why is getting something I can do on my console with `git branch` so hard in a GHA environment?

Getting something as basic as the current branch name shouldn't require custom bash scripting depending on the context.  Github, please make this easy for us.

**Comment by jeremybusk** [comment]
https://docs.github.com/en/actions/learn-github-actions/variables is really unclear. Please get better examples. It shouldn't be that hard. If you can't do this just tell people to write their own logic in bash or pwsh or use gitlab.

**Comment by piotrekkr** [comment]
It is even more weird with `pull_request` event. I'm using this code to pass env vars to an action :

```
  env:
    COMMIT_INFO_BRANCH: ${{ github.ref_name }}
    COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
    COMMIT_INFO_SHA: ${{ github.sha }}  
```

Branch name for PR is `chore/ci-setup`. In logs I get this:

```
  env:
    COMMIT_INFO_BRANCH: 3/merge
    COMMIT_INFO_MESSAGE: chore(ci): setup
    COMMIT_INFO_SHA: fbf88412867d6d0475da156e1ad3deb2d02c43e9
```

Who would ever want `3/merge` to be returned for ref name?!

**Comment by VioletHynes** [comment]
Just wanted to add support for this issue. I was very confused as to why a GHA was skipping my branch and it was because the `github.ref_name` wasn't accurate, which isn't something the documentation warns about. It makes it really sound like it's the way to get the branch name in all cases, and it's confusing that I need to use `head_ref` for PRs, but `ref_name` for non-PRs.

I think there'd be beneficial to have a `github.branch_name` that works universally, and gives you the branch name irrespective of how it's ran or triggered, but I also think the docs are a little misleading as-is.

**Comment by cmwilson21** [comment]
👋 Hey folks! Thanks for all the great feedback in this issue. We had this as an open issue for anyone to work on, but after reviewing it, we are going to remove it from the `help wanted` board and discuss it a bit further. 

Thanks again for all your input! 💖

**Comment by ryan-williams** [comment]
I have a step like this at the start of most workflows:

```yml
- run: echo "REF=${{ github.event.pull_request && github.head_ref || github.ref_name }}" >> $GITHUB_ENV
```

which lets me reference `$REF` in subsequent steps, to abstract over this `head_ref`/`ref_name` inconsistency.

**Comment by piotrekkr** [comment]
@ryan-williams Thanks for your example. I did not know there was ternary available in expression until I saw your example. Must have missed in in [docs](https://docs.github.com/en/actions/learn-github-actions/expressions#example). Super handy to know about this.

**Comment by radekjezdik** [comment]
Just to add to this **valid** ticket: the documentation is also inconsistent in the same description of `GITHUB_REF`.

> For workflows triggered by pull_request, **this is the pull request merge branch**. 

Which is not true and contradicts with the later example:

> The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, **for pull requests it is refs/pull/<pr_number>/merge**, and for tags it is refs/tags/<tag_name>. For example, refs/heads/feature-branch-1

**Comment by igiona** [comment]
> 👋 Hey folks! Thanks for all the great feedback in this issue. We had this as an open issue for anyone to work on, but after reviewing it, we are going to remove it from the `help wanted` board and discuss it a bit further.
> 
> Thanks again for all your input! 💖

Does it mean you're on it, or that we're going to wait another year or two for this simple feature? By then, nearly everyone got a workaround in place...

**Comment by mering** [comment]
3 days pass quickly nowadays...

**Comment by danielricecodes** [comment]
What a shame to let a bit close this. This is such an easy win for GitHub and not hard for even a junior engineer to implement.

**Comment by igiona** [comment]
A simple and generic way to get the current branch name is still required and would be much appreciated.
Thanks for considering this issue.

**Comment by piotrekkr** [comment]
I recently learned that even using some bash condition can fail to figure out the ref name for current workflow run. Idk how GitHub runners work but this workflow step fails randomly (like 10% of times). I have already sent an issue about this to GitHub support.

I have a workflow that is run on `release` and `workflow_dispatch` events. When this workflow is triggered by publishing new release it is randomly failing because GITHUB_REF and github.ref is not set. We use some bash logic to handle both release and workflows_dispatch GIT ref like this:

```
name: 01 - Deploy To Staging

concurrency: staging

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release_ref:
        description: "Release TAG"
        required: true

jobs:
  initialize:
    name: "Initialize deploy"
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    outputs:
      ref: "${{ steps.version.outputs.ref }}"
    steps:
      - name: Get git ref
        id: git_ref
        run: |
          if [[ "${{ github.event_name }}" = "release" ]]; then
            echo "value=${{ github.ref }}" >> $GITHUB_OUTPUT
          else
            echo "value=${{ github.event.inputs.release_ref }}" >> $GITHUB_OUTPUT
          fi

# next steps are failing because they expect `steps.git_ref.outputs.value` or `GITHUB_REF` to be set
```

90% of times this works fine:

![image](https://github.com/github/docs/assets/503782/2bd6879b-8873-4311-b8a1-130e45246625)

but in 10% of cases it fails:

![image](https://github.com/github/docs/assets/503782/7286fb93-2ffa-484d-a0e5-068e581b9bdf)

Based on GitHub docs about `github.ref` it should be always set for both of those events:

> The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by push, this is the branch or tag ref that was pushed. For workflows triggered by pull_request, this is the pull request merge branch. For workflows triggered by release, this is the release tag created. For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is refs/heads/<branch_name>, for pull requests it is refs/pull/<pr_number>/merge, and for tags it is refs/tags/<tag_name>. For example, refs/heads/feature-branch-1.

Also this randomness is not just happening inside one repository workflow runs. When it happens it happens for multiple repositories at similar time.

Really weird stuff going on.
