### ISSUE TITLE
GitHub Actions docs: inconsistency of YAML indentation between dashes

### ISSUE THREAD

**Issue by justanotheranonymoususer** [github/docs#1546]
See this question:
https://stackoverflow.com/questions/17014460/yaml-indentation-for-array-in-hash

The docs are not consistent regarding YAML indentation between dashes.

Example:
[Using Flake8 to lint code](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#using-flake8-to-lint-code):
```yaml
steps:
- uses: actions/checkout@v2
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.x'
...
```

[Running tests with tox](https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#running-tests-with-tox):
```yaml
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
...
```

There are many other examples of inconsistency, between different snippets and sometimes within a single snippet. That's confusing, I suggest to agree on a convention and stick to it.
