### ISSUE TITLE
Provide example of using an output to define two matrixes

### ISSUE THREAD

**Issue by jsoref** [github/docs#17748]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-contexts-to-create-matrices

### What part(s) of the article would you like to see updated?

Provide an example of using an output for two matrixes.

Often people will want to define a nontrivial matrix and then realize that they want to use it for more than one job and know that they don't want to copy and paste the definition because that's brittle. But they won't know how to share the definition for use by more than one matrix job.

### Additional information

This question comes up often enough, e.g. here:

https://github.community/t/can-i-share-strategy-matrices-between-multiple-jobs/195827/7

Sadly, as you can see, people often get/give the wrong answer (no, you can't). Since it's definitely possible, and actually fairly easy, but not terribly obvious, it'd be helpful if it were documented.

---
[maintainers edit]
See comments below for content creation ideas.

**Comment by juliandunn** [comment]
That seems reasonable to me, that we would just include an example like [this](https://github.community/t/can-i-share-strategy-matrices-between-multiple-jobs/195827/7)

**Comment by jsoref** [comment]
That fragment is a good start.

My preference would be to also include a sample `createMatrices` job to show setting the output with a matrix.

Thoughts?

**Comment by juliandunn** [comment]
Sure. Do you have one handy that works?

**Comment by jsoref** [comment]
Hmm, I kinda wish I had left a breadcrumb. My current adventure involves setting `runs-on` and not `matrix`. I'm not sure offhand how to search my GitHub activity to find one.

I think it's best to ask someone else to work on this, I'm going to be very busy for the next month and really won't have time to work on this (or any of the other items I'm filing).

**Comment by cmwilson21** [comment]
Sounds great then, thanks for letting me know. 👍

**Comment by notsosimppole** [comment]
Hey, I would like to work on this but I didn't quite get the type of example one would be looking for here.

**Comment by jsoref** [comment]
The general idea would be a dynamic matrix where one phase produces binaries and a second phase tests them.

**Comment by jsoref** [comment]
@cmwilson21 😦

**Comment by felicitymay** [comment]
👋🏻 @juliandunn 

We're reviewing all open help wanted issues as part of our preparation for Hacktoberfest next week.

Sadly the link you provided to a simple example in https://github.com/github/docs/issues/17748#issuecomment-1151724407 was lost when we migrated our community to discussions. Are you able to help with a new example?

**Comment by jsoref** [comment]
This [workflow](https://github.com/check-spelling-sandbox/shared-matrixes-0/actions/runs/8071877001) should be good enough:

```yaml
name: shared matrix
on:
  push:
  workflow_dispatch:

jobs:
  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      colors: ${{ steps.colors.outputs.colors }}

    steps:
      - name: Define Colors
        id: colors
        run: |
          echo 'colors=["red", "green", "blue"]' >> "$GITHUB_OUTPUT"

  produce-artifacts:
    runs-on: ubuntu-latest
    needs: define-matrix
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}

    steps:
      - name: Define Color
        env:
          color: ${{ matrix.color }}
        run: |
          echo "$color" > color
      - name: Produce Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.color }}
          path: color

  consume-artifacts:
    runs-on: ubuntu-latest
    needs:
    - define-matrix
    - produce-artifacts
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.colors) }}

    steps:
    - name: Retrieve Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.color }}
      
    - name: Report Color
      run: |
        cat color
```

Thoughts?
