### ISSUE TITLE
`jobs` context isn't listed as a context in the Contexts article

### ISSUE THREAD

**Issue by jsoref** [github/docs#17823]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts

### What part(s) of the article would you like to see updated?

Add a

> ## Jobs context
>
> Insert text explaining its structure. It's probably just a `jobs.`_job-id_`.`_job-context-content_ but maybe it isn't?
>
> There should be a reminder that the _job-id_ is just the label for the item under `jobs:` in the yaml -- it comes up periodically that people expect:
>
> ```
> jobs:
>   something:
>     id: an-id
> ```

### Additional information

Workflow key | Context | Special functions
-- | -- | --
concurrency | github, inputs |  
jobs.<job_id>.steps.working-directory | github, needs, strategy, matrix, **job**, runner, env, secrets, steps, inputs | hashFiles
on.workflow_call.outputs.<output_id>.value | github, _jobs_ [this is not defined as a context on this page], inputs

**Comment by steveward** [comment]
Thanks @jsoref! I'll mark this for someone to review to confirm.

**Comment by ChristopherHX** [comment]
_Not a typo..., but unclear / incomplete documentation_
```yaml
on:
   workflow_call:
     outputs:
       A:
         value: ${{ jobs.my_job.outputs.A }} # jobs is equivalent to the needs context and has the same structure, but includes all jobs in the current workflow file
jobs:
  my_job:
    outputs:
      A: MyOutput
    runs-on: ubuntu-latest
    steps:
    - run: exit 0
```

**Comment by jsoref** [comment]
Indeed, so, it isn't that it's a typo, it's that the `jobs` context isn't listed on this page at all.

Obviously, it should be.

I'll change the issue description after we get confirmation...

**Comment by lucascosti** [comment]
👋 Thanks for opening this issue!

🤔 Yes, this is a bit complicated. For regular workflows, there is no `jobs` context. The `jobs` context only applies to reusable workflows (i.e. workflows with an `on.workflow_call` trigger), but I'm not 100% sure on where it can be used or what's in it; it might only be available to set outputs in the called workflow. I'll have to check in with engineering.

**Comment by ajaykn** [comment]
@lucascosti Thats right, this is available for reusable workflows while setting the output values.

Something like this:
```
 workflow_call:
    outputs:
      output1:
        value: ${{ toJSON(jobs.job1) }}
      output2:
        value: ${{ toJSON(jobs.job2) }}
```

and output1 data can look like:
```
{
  result: success,
  outputs: {
    output1: hello2,
    output2: world2
  }
}
```
