### ISSUE TITLE
Unclear when to use expression syntax with literals

### ISSUE THREAD

**Issue by schalkneethling** [github/docs#17869]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions#literals

### What part(s) of the article would you like to see updated?

The [following section](https://docs.github.com/en/actions/learn-github-actions/expressions#literals) talks about the literal data types used with expression syntax. The example that follows seems to indicate that when specifying anything that is not meant to be a string should be set using expression syntax.

However, if one attempts to do this in, for example, the [`inputs` section of a workflow](https://github.com/project-calavera/calavera-reusable-actions/blob/7ddf5e2fe2108c91da05a269c4e0f56b5e40f8b5/.github/workflows/publish-release.yml#L19), the validator shows an error that is quite the opposite:

![Screenshot of validator tooltip status that a boolean was expected, but instead it got a string](https://user-images.githubusercontent.com/10350960/168480544-75c9afcf-c02f-4b01-a412-3c5bb51543d7.png)

On re-reading this part, I assume it is referring specifically to when setting environmental variables?

**Comment by steveward** [comment]
Thanks @schalkneethling, I'll get this triaged for review.

**Comment by gsrohde** [comment]
@schalkneethling 

Experimenting with using templates for *workflow_dispatch* inputs, I found the following to be true:

1. No matter what the input type, if I tried to use `default: ${{ true }}`, I got a workflow error: "A template expression is not allowed in this context"
2. In spite of this, I could use `default: ${{ 'true' }}` without getting a workflow error.  However, doing this was never useful:
    a. Using `default: ${{ 'true' }}` when the input type was boolean resulted in the input checkbox *not* being checked, and the the default value was treated as false.
    b. Using `default: ${{ 'true' }}` when the input type was specified to be a string would literally display the default `${{ 'true' }}` in the input text box.  Actually trying to display this input value with a _Bash_ statement such as `echo "The string you entered is: ${{ github.event.inputs.my_string_input }}"` would cause the workflow to error out at that point in the workflow with the error "The string you entered is: ${{ 'true' }}: bad substitution".  In fact, the question of setting defaults aside, _any_ string input that looks like an expression template is likely to cause the workflow to crash: there doesn't seem to be any escaping of syntactically-significant input characters.
3. The declared type of an input seems only to affect how input entry is presented to the user: _boolean_ types present as a check box, _choice_ types present as a dropdown, and _string_ types present as a text box.  By the time you use `github.event.inputs.my_input`, that value has been _cast_ or _converted_ to a string, seemingly according to the rules outlined in the [_Learn GitHub Actions_ section on functions](https://docs.github.com/en/actions/learn-github-actions/expressions#functions).  For example, even if you give input variable `my_boolean` type "boolean" and check the resulting input box when you run the workflow, `${{ github.event.inputs.my_boolean == 'true' }}` will evaluate to _true_, but `${{ github.event.inputs.my_boolean == true }}` will evaluate to _false_.

I think the way inputs are treated in the context of *workflow_call* events is significantly different, but I'm still testing this out.

By the way, **what validator did you use to get the above screen shot?**

**Comment by schalkneethling** [comment]
> By the way, **what validator did you use to get the above screen shot?**

That was GitHub’s native in-browser workflow editor.

**Comment by gsrohde** [comment]
> That was GitHub’s native in-browser workflow editor.

Thanks.  For what it's worth, the validator gives me a slightly different error for the case you mention—namely, "type is set to boolean but default has invalid value".  If the type is set to string, however, the validator doesn't complain _at all_ about a default of `${{ true }}`; but trying to run a workflow with this default immediately errors out with the message "A template expression is not allowed in this context", as I mentioned in point 1 above.

As for using template expressions for setting environment, it seems they _can_ be used, but needn't be if one is merely setting an environment variable to a literal value.  All of the following, for example, result in the expression `${{ env.true-string-* == 'true' }}` evaluating to _true_ (and `${{ env.true-string-* == true }}` evaluating to _false_!), where * is a number 1 through 6.
```
env:
  true-string-1: true
  true-string-2: ${{ 'true' }}
  true-string-3: 'true'
  true-string-4: !!bool true
  true-string-5: ${{ true }}
  true-string-6: ${{ fromJSON(true) }}
```

**Comment by gsrohde** [comment]
[@schalkneethling: While the following comment might be of interest to you if you use *called workflows*, it is primarily motivated by the hope that @steveward or whoever from the GitHub team works on this issue will see fit to either uniformize the behavior of *workflow_dispatch* inputs and *workflow_call* inputs or rewrite or add to the documentation in order to make clear how they work very differently.]

As I hinted in my first comment, the way inputs are treated in the context of *workflow_call* events is significantly different from how they are treated in the context of a *workflow_dispatch* event.  For example,

1. Using the expression syntax (${{ }}) to set a default for a *workflow_call* input is perfectly acceptable.  Even the on-line validator agrees: if you change *workflow_dispatch* to *workflow_call* in the example above that flagged `default: ${{ true }}` as an error, you will see that error message disappear.

    While there really isn't any good reason to use `${{ true }}` here instead of just `true`, there may be use cases where using expression syntax might be of some value.  For example, you could use an expression like `${{ format('The event is {0}!', github.event_name) }}` to set the default value of a `workflow_call` input of type _string_.

2. The context expression for *workflow_call* inputs is simpler: `inputs.my_input` is used rather than `github.event.inputs.my_input`.
3.  A *workflow_call* input declared as boolean _really is_ treated as a boolean value when used.  For example, consider a *workflow_dispatch* input and a *workflow_call* input, both declared as _boolean_, both named `true_boolean_value`, and both set to or defaulted to _true_ in a run of the workflow.  Then (as I pointed out earlier), `${{ github.event.inputs.true_boolean_value == 'true' }}` will evaluate to true, but `{{ github.event.inputs.true_boolean_value == true }}` will evaluate to false.  With the *workflow_call* input, we have the reverse: `${{ inputs.true_boolean_value == 'true' }}` evaluates to false, but `${{ inputs.true_boolean_value == true }}` evaluates to true.

    Note that if you have a caller workflow that has (*workflow_dispatch*) boolean input `true_boolean_value`, and you want to pass this through to a called workflow having a like-named boolean input, you have to first convert the *workflow_dispatch* value to a bona fide boolean, e. g.
```
  call-reusable-workflow-boolean:
    uses: ./.github/workflows/reusable.yaml
    with:
      true_boolean_value: ${{ github.event.inputs.true_boolean_value == 'true' }}
```
or
```
  call-reusable-workflow-boolean:
    uses: ./.github/workflows/reusable.yaml
    with:
      true_boolean_value: ${{ fromJSON(github.event.inputs.true_boolean_value) }}
```
Just doing
```
  call-reusable-workflow-boolean:
    uses: ./.github/workflows/reusable.yaml
    with:
      true_boolean_value: ${{ github.event.inputs.true_boolean_value }}
```
will result in a type error, because `${{ github.event.inputs.true_boolean_value }}` is seen as a string, and you can't pass a string for the value of a (`workflow_call`) input declared to be a boolean.

**Comment by lucascosti** [comment]
Thanks for opening this, @schalkneethling. I _think_ inputs can only provided as strings, but you can set the type using `type`, so

```yaml
npm-publish:
  description: Whether to publish the package to npm
  default: true
  required: false
  type: boolean
```

 is valid for specifiying an input that is a boolean (using strings in YAML)

but forcing an expression to be a boolean is not valid YAML for GitHub Actions, e.g. this wouldn't be valid:

```yaml
npm-publish:
  description: Whether to publish the package to npm
  default: ${{ true}}
  required: false
  type: boolean
```

> On re-reading this part, I assume it is referring specifically to when setting environmental variables?

I think you're right, but will get an SME to confirm

**Comment by gsrohde** [comment]
> Thanks for opening this, @schalkneethling. I _think_ inputs can only provided as strings, but you can set the type using `type`, so
> 
> ```yaml
> npm-publish:
>   description: Whether to publish the package to npm
>   default: true
>   required: false
>   type: boolean
> ```
> 
> is valid for specifiying an input that is a boolean (using strings in YAML)
> 
> but forcing an expression to be a boolean is not valid YAML for GitHub Actions, e.g. this wouldn't be valid:
> 
> ```yaml
> npm-publish:
>   description: Whether to publish the package to npm
>   default: ${{ true}}
>   required: false
>   type: boolean
> ```
> 
> > On re-reading this part, I assume it is referring specifically to when setting environmental variables?
> 
> I think you're right, but will get an SME to confirm

@lucascosti As I point out in [my comment above](https://github.com/github/docs/issues/17869#issuecomment-1137645672), using
```
npm-publish:
  description: Whether to publish the package to npm
  default: ${{ true}}
  required: false
  type: boolean
```
works perfectly well in the context of `on.workflow_call.inputs`, even though the on-line validator may flag it as a type error.  (And as I also point out, it _doesn't_ work in the context of `on.workflow_dispatch.inputs`.)
