### ISSUE TITLE
Document security policy being shown along with issue templates

### ISSUE THREAD

**Issue by oplik0** [github/docs#18798]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

### What part(s) of the article would you like to see updated?

Currently the docs don't seem to mention the fact that security policy is shown on the issue template chooser, and the [configure](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) section specifically has an example with a link to bug bounty:
```yaml
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
```
This, combined with it being quite inconvenient to test the templates due to them only working on the default branch, means it's quite possible to accidentally create a redundant contact link for security information.

As such I think it'd be a good idea to clarify that security policy will be also be shown alongside issue templates and perhaps add it to the screenshot of the issue template chooser in the article.

### Additional information

An example of me adding a redundant link due to not knowing that security policy would be displayed can be seen in NodeBB repo: https://github.com/NodeBB/NodeBB/pull/10720 (and the PR fixing it: https://github.com/NodeBB/NodeBB/pull/10723)
![example of redundant `Security Issues` link below the default `Report a security vulnerability` link to the security policy](https://user-images.githubusercontent.com/25460763/175570200-36ad0281-3076-47b0-ae88-34e00822fd14.png)
