### ISSUE TITLE
Update cache action with correct snippet for Java-Maven example.

### ISSUE THREAD

**Issue by vinzydev** [github/docs#19566]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

### What part(s) of the article would you like to see updated?

Caching dependencies
You can cache your dependencies to speed up your workflow runs. After a successful run, your local Maven repository will be stored in a cache. In future workflow runs, the cache will be restored so that dependencies don't need to be downloaded from remote Maven repositories. You can cache dependencies simply using the [setup-java action](https://github.com/marketplace/actions/setup-java-jdk) or can use [cache action](https://github.com/actions/cache) for custom and more advanced configuration.

YAML

```
``steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
      cache: maven
  - name: Build with Maven
    run: mvn --batch-mode --update-snapshots verify
```

### Additional information

This can be corrected by updating as below

``- name: Cache local Maven repository
  uses: actions/cache@v3
  with:
    path: ~/.m2/repository
    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
    restore-keys: |
      ${{ runner.os }}-maven-``
