### ISSUE TITLE
Incorrect type of `string` for `github.ref_protected` property

### ISSUE THREAD

**Issue by chrismuellner** [github/docs#20456]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

### What part(s) of the article would you like to see updated?

type for property `github.ref_protected` is of type `string` according to the table, but is of type `boolean` in both the [example contents of the github context](https://docs.github.com/en/actions/learn-github-actions/contexts#example-contents-of-the-github-context) and actual usage.

The following snippet skips the step on a protected branch:
```yaml
...
jobs:
  debug:
    name: Protected check
    runs-on: ubuntu-latest
    if: github.ref_protected == 'true'
...
```

The following snippet runs the job on a protected branch:
```yaml
...
jobs:
  debug:
    name: Protected check
    runs-on: ubuntu-latest
    if: github.ref_protected
...
```
