### ISSUE TITLE
Issue event `assigned` does not have `assigner`

### ISSUE THREAD

**Issue by yanyongyu** [github/docs#20795]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#assigned

https://docs.github.com/en/developers/webhooks-and-events/events/issue-event-types#unassigned

### What part(s) of the article would you like to see updated?

https://github.com/github/docs/blob/fed0a6c56ee6c6cce63ff06ac760edc5439aa7d7/data/reusables/issue-events/assignee-properties.md?plain=1#L1-L2

As described in the `github/rest-api-description` repo, the timeline api returns the `assigned` event as follows:

```yaml
timeline-assigned-issue-event:
  title: Timeline Assigned Issue Event
  description: Timeline Assigned Issue Event
  type: object
  properties:
    id:
      type: integer
    node_id:
      type: string
    url:
      type: string
    actor:
      "$ref": "#/components/schemas/simple-user"
    event:
      type: string
    commit_id:
      type:
      - string
      - 'null'
    commit_url:
      type:
      - string
      - 'null'
    created_at:
      type: string
    performed_via_github_app:
      anyOf:
      - type: 'null'
      - "$ref": "#/components/schemas/integration"
    assignee:
      "$ref": "#/components/schemas/simple-user"
```

the field `assigner` is not included.
