### ISSUE TITLE
on.workflow_call.inputs.<input_id>.type includes invalid type ("choice")

### ISSUE THREAD

**Issue by andy-crain-kr** [github/docs#21324]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype

In the following text (url above):
> on.workflow_call.inputs.<input_id>.type
Required if input is defined for the on.workflow_call keyword. The value of this parameter is a string specifying the data type of the input. This must be one of: boolean, number, string or choice.

"choice" is not a valid type (unlike for workflow_dispatch, where it is valid). A resuable workflow like this:
```yaml
on:
    workflow_call:
        inputs:
            foo:
                required: true
                type: choice
                default: 'bar'
                options:
                    - biz
                    - bar
``` 
...results in an error message like this:
> [Invalid workflow file: .github/workflows/#######](https://github.com/######/actions/runs/#####/workflow)
The workflow is not valid. #####/.github/workflows/#####@##### (Line: 6, Col: 23): Unexpected value 'choice' #####/.github/workflows/terraform.yaml@###### (Line: 8, Col: 17): Unexpected value 'options'

### What part(s) of the article would you like to see updated?

"choice" should be removed as a valid option
