### ISSUE TITLE
"Handling skipped but required checks" promises a non-viable solution

### ISSUE THREAD

**Issue by TWiStErRob** [github/docs#21865]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[Handling skipped but required checks](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks) which is also linked from [on.<push|pull_request|pull_request_target>.<paths|paths-ignore>](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths).

### What part(s) of the article would you like to see updated?

The whole solution might be invalid and shouldn't be advertised.
The solution described in the help article doesn't scale to more than 1 job.

### Additional information

Here's an example applied to 2 projects (removed newlines so that it fits on one screen 😅):
```yaml
name: project 1 ci
on: pull_request: paths: - 'project1/**'
jobs: build1: steps: - run: 'some ci'
```
```yaml
name: project 1 standin
on: pull_request: paths-ignore: - 'project1/**'
jobs: build1: steps: - run: 'echo "No build required"'
```

```yaml
name: project 2 ci
on: pull_request: paths: - 'project2/**'
jobs: build2: steps: - run: 'some ci'
```

```yaml
name: project 2 standin
on: pull_request: paths-ignore: - 'project2/**'
jobs: build2: steps: - run: 'echo "No build required"'
```

(If links are not working you can repro from [archive](https://github.com/TWiStErRob/repros/tree/master/github/actions-skipped-ci).)

| Changes | project 1 ci<br>`build1` | project 1 standin<br>`build1` | project 2 ci<br>`build2` | project 2 standin<br>`build2` | comment |
|-|-|-|-|-|-|
| [&bull; project1/\*\*](https://github.com/TWiStErRob/repro-skipped-ci/pull/1) | ✅ | 🚫 | 🚫 | ✅ | as documented |
| [&bull; project2/\*\*](https://github.com/TWiStErRob/repro-skipped-ci/pull/2) | 🚫 | ✅ | ✅ | 🚫 | as documented |
| [&bull; project3/\*\*](https://github.com/TWiStErRob/repro-skipped-ci/pull/3) | 🚫 | ✅ | 🚫 | ✅ | as expected |
| [&bull; project1/\*\*<br>&bull; project2/\*\*](https://github.com/TWiStErRob/repro-skipped-ci/pull/4) | ✅ | ✅ | ✅ | ✅ | what?! |

This last row is what bothers me.
 * I think @scherroman also alluding to this in [community/discussions#26251](https://github.com/orgs/community/discussions/26251#discussioncomment-3250969).
 * @steve21168 and @thispsj discussed this at https://github.com/github/docs/pull/9126

It is expected as per documentation because `project2/some/file` matches both `paths: project2/**` and `paths-ignore: project1/**` and vice versa. At this point I have no idea what to do, because as it stands this solution is not too useful in a general case, so maybe a big warning that it only works on 1 thing and [not even for that in case you change the path and something else](https://github.com/github/docs/pull/9126#issuecomment-1118118625). I would also like to also invoke @jsoref @lecoursen who were originally involved.

The standin job might have some side-effects (e.g. create other required status checks to make the branch protection pass), in which case the acceptance of the multi-execution is not viable.
