### ISSUE TITLE
Workflow job execution doc should clarify that 'env' context is not available in job 'if' conditional

### ISSUE THREAD

**Issue by neilotoole** [github/docs#21927]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

### What part(s) of the article would you like to see updated?

The doc has an example:

```yaml
name: example-workflow
on: [push]
jobs:
  production-deploy:
    if: github.repository == 'octo-org/octo-repo-prod'
```

I spent several hours trying to access `env.MY_ENVAR`, running into errors, before finally realizing that the `env` context cannot be accessed until after the job runner has been instantiated (which happens after the `if` guard has passed).

The doc should be updated to clarify that the `env` context is not available in the `if` conditional of a `job`.
