### ISSUE TITLE
Using gh in an workflow seems to require setting GH_TOKEN

### ISSUE THREAD

**Issue by mkutz** [github/docs#21930]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

### What part(s) of the article would you like to see updated?

When I try the suggested workflows I get an error as `gh` seems to need the `GITHUB_TOKEN` to be set as `GH_TOKEN`.

The following works:

```
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

### Additional information

The repo in question is private and within an organization.
