### ISSUE TITLE
Fix syntax example

### ISSUE THREAD

**Issue by Dunky-Z** [github/docs#22820]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

translations/zh-CN/content/actions/migrating-to-github-actions/migrating-from-gitlab-cicd-to-github-actions.md

### What part(s) of the article would you like to see updated?

```yaml
windows_job:
  tags:
    - windows
  script:
    - echo Hello, %USERNAME%!

linux_job: tags:
    - linux script:
    - echo "Hello, $USER!"
```
shoud be wrap

```yaml
windows_job:
  tags:
    - windows
  script:
    - echo Hello, %USERNAME%!

linux_job: 
  tags:
    - linux 
  script:
    - echo "Hello, $USER!"
```
