### ISSUE TITLE
The example YAML in the issue form schema is incorrect

### ISSUE THREAD

**Issue by stockholmux** [github/docs#23053]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#about-githubs-form-schema

### What part(s) of the article would you like to see updated?

In the example YAML under the section "About GitHub's form schema" is incorrect and will render JSON in the resulting form dropdown. This section:

```yaml
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - label: 1.0.2 (Default)
      - label: 1.0.3 (Edge)
```

In `attributes.options` having `label:` before the drop down item text will result in the following rendering:

![Screen Shot 2023-01-06 at 3 05 33 PM](https://user-images.githubusercontent.com/1152927/211108984-dea9b76b-3036-4d59-b8cd-337a63da9588.png)

Removing `label` will correct the issue:

```yaml
- type: dropdown
  attributes:
    label: Version
    description: What version of our software are you running?
    multiple: false
    options:
      - 1.0.2 (Default)
      - 1.0.3 (Edge)
```

Yielding:
![Screen Shot 2023-01-06 at 3 18 04 PM](https://user-images.githubusercontent.com/1152927/211109363-3946ac85-9ad8-405f-aec0-1ccd09a69568.png)
