### ISSUE TITLE
Seemingly wrong limitation on GitHub Actions reusable workflow and composite action

### ISSUE THREAD

**Issue by micnncim** [github/docs#23572]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows

### What part(s) of the article would you like to see updated?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

> You cannot use a reusable workflow from another repository if it uses a composite action. For more information, see "About custom actions."

That said, turns out it's possible to do - below are the details of testing:

Composite action:

```yaml
# .github/actions/test/action.yml
name: Test

on:
  workflow_call:
    inputs:
      foo:
        type: string
        description: Foo
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Echo
        run: echo "Hello from reusable workflow! inputs.foo=${{ inputs.foo }}"

      - name: Run composite action
        uses: micnncim/test-gha-composite-action/.github/actions/test@main
        with:
          foo: ${{ inputs.foo }}
```

Reusable workflow:

```yaml
# .github/workflows/_test.yml
name: Test

on:
  workflow_call:
    inputs:
      foo:
        type: string
        description: Foo
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Echo
        run: echo "Hello from reusable workflow! inputs.foo=${{ inputs.foo }}"

      - name: Run composite action
        uses: micnncim/test-gha-composite-action/.github/actions/test@main
        with:
          foo: ${{ inputs.foo }}
```

Workflow using the reusable workflow:

```yaml
# .github/workflows/test.yml
name: Test

on:
  workflow_dispatch:
    inputs:
      foo:
        description: Foo
        required: true

jobs:
  test:
    uses: micnncim/test-gha-composite-action/.github/workflows/_test.yml@main
    with:
      foo: ${{ github.event.inputs.foo }}
```

Workflow run result:

![Screen Shot 2023-01-30 at 14 28 12](https://user-images.githubusercontent.com/21333876/215395764-19f96e41-f869-4380-ba0d-f4e6940c4c4f.png)

The repositories used for the testing are available on [micnncim/test-gha-composite-action](https://github.com/micnncim/test-gha-composite-action) and [micnncim/test-gha-reusable-workflow](https://github.com/micnncim/test-gha-reusable-workflow).
