### ISSUE TITLE
Actions: Expand `secrets: inherit` documentation

### ISSUE THREAD

**Issue by JLLeitschuh** [github/docs#24366]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow

### What part(s) of the article would you like to see updated?

'Passing inputs and secrets to a reusable workflow'

The documentation on `secrets: inherit` is fairly limited, and could use some expanding upon to be clearer.

> Workflows that call reusable workflows in the same organization or enterprise can use the `inherit` keyword to implicitly pass the secrets.

Implicitly passed how? From what? This could use a bit of love to better explain how it works and how to utilize the feature.

A larger example of how this feature works would greatly assist in end users understanding how to actually utilize it in their own builds.

**Comment by guidodobboletta** [comment]
This would definitely be nice as I'm also exploring the possibility of using `secrets: inherit` but there's 0 details on how this feature works.

**Comment by JLLeitschuh** [comment]
Tragic, this is a fairly straightforward feature, that's just under documented.

**Comment by emmanuelnk** [comment]
Is there any progress on this? Its August now. Even a simple example on how to use this feature would help.

**Comment by emmanuelnk** [comment]
For anyone who lands on this, here's my attempt at documenting this better with an example.

If you have either secrets defined at the ORGANIZATION level OR secrets defined In `REPOSITORY_A` , the reusable workflow (that lives in `REPOSITORY_B` can inherit all these secrets that `REPOSITORY_A` has access to)

## Example
Let's assume you have the secret  `TEST_DB_PASSWORD` defined either as an `ORGANIZATION` secret or `REPOSITORY_A` secret

In `REPOSITORY_A/.github/workflows/caller-workflow.yml`:
```yml
name: Caller Workflow

on:
   #...
   #...

jobs:
  CallReusableWorkflowJob:
     uses: ORGANIZATION/REPOSITORY_B/.github/workflows/reusable-workflow.yml@main
     secrets: inherit
```

In In `REPOSITORY_B/.github/workflows/reusable-workflow.yml` :
```yml
name: Reusable Workflow

on: 
  workflow_call:
  
 jobs:
  SomeJob:
      runs-on: ubuntu-latest
      steps:  
        - name: Use inherited secret
           run: psql -p ${{ secrets.TEST_DB_PASSWORD }}

             
   #...
   #...
```

As you can see you don't need to define the secrets object in `reusable-workflow.yml` since it will inherit all the secrets from `REPOSITORY_A` and thus `TEST_DB_PASSWORD` will be defined.

## Limitations:
It's also important to note that `reusable-workflow.yml` can only use secrets from the repository it is called from (i.e. `REPOSITORY_A` -- it cannot use secrets defined in `REPOSITORY_B` if it was called from `REPOSITORY_A`
