### ISSUE TITLE
Composite example does not work on ubuntu + container

### ISSUE THREAD

**Issue by AllanOricil** [github/docs#24836]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/creating-a-composite-action

### What part(s) of the article would you like to see updated?

This [part](https://docs.github.com/en/enterprise-cloud@latest/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file) of the article says that if I add the actions path to GITHUB_PATH, the workflow should be able to use executables that are on the action's directory. But it does not work.

### Additional information

This is my action

<img width="457" alt="image" src="https://user-images.githubusercontent.com/55927613/229501701-44567b9a-493c-4d7a-a339-c83cd549a49a.png">

````yml
name: Compute Salesforce Metadata Changes
description: Compute Salesforce Metadata Changes using the sgd plugin for sfdx
author: allanoricil
inputs:
  from:
    description: commit sha from where the diff is done [git rev-list --max-parents=0 HEAD]
    required: true
  output-directory:
    description: source package specific output
    required: true
outputs:
  has_package_changes:
    description: it returns true if there are package changes
    value: ${{ steps.compute_metadata_changes.outputs.has_package_changes }}
  has_destructive_changes:
    description: it returns true if there are destructive changes
    value: ${{ steps.compute_metadata_changes.outputs.has_destructive_changes }}
runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: env
      shell: bash
    - id: compute_metadata_changes
      run: compute-metadata-changes.sh
      shell: bash
````

This is the workflow that is using this action

````yml
name: Composite Action

on:

  workflow_dispatch:
    inputs:
      FROM:
        type: string
        required: true
        description: "compute diffs from a hash reference"
      OUTPUT_DIRECTORY:
        type: string
        required: true
        description: "output directory"

jobs:

  composite-action:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vodafoneis/salesforce-build-image:v1.12.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set repo as a safe directory
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"

      - name: Compute Metadata Changes
        uses: VodafoneIS/compute-metadata-changes-composite@v0.0.0
        id: compute_metadata_changes
        with:
          from: ${{ inputs.FROM }}
          output-directory: ${{ inputs.OUTPUT_DIRECTORY }}

      - name: Print Outputs
        run: |
          echo "has_package_changes: ${{ steps.compute_metadata_changes.outputs.has_package_changes }}"
          echo "has_destructive_changes: ${{ steps.compute_metadata_changes.outputs.has_destructive_changes }}"

````

This is the workflow log: 
[logs_27.zip](https://github.com/github/docs/files/11137948/logs_27.zip)

As you can see in the following image, compute-metadata-changes.sh can't be found even after running `echo "${{ github.action_path }}" >> $GITHUB_PATH` as described in the doc

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/55927613/229502017-0fe85cea-c7e7-477e-aeec-b3af1c9a0827.png">

I noticed that GITHUB_PATH was not changed, but PATH was
<img width="714" alt="image" src="https://user-images.githubusercontent.com/55927613/229502867-9b60ae54-90a0-48e0-af63-32713aca086f.png">

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/55927613/229503066-a511f77c-87c5-4f23-911a-ff7bf6d3f358.png">
