### ISSUE TITLE
Unclear if `ignore` option in dependabot configuration also ignores security updates

### ISSUE THREAD

**Issue by audryhsu-ookla** [github/docs#24966]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

### What part(s) of the article would you like to see updated?

I would like to configure dependabot to limit **version** alerts to only semver major updates by using the `ignore` option to filter out any dependencies for minor and patch version. However, I do NOT want to ignore any **security** alerts. 

The documentation is unclear to me how setting the `ignore` option in the dependabot.yml will affect whether security updates will raised on my repository's default (main) branch. 

In [this paragraph](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore), the last bullet says that security updates are NOT affected by using `ignore`.`update-types` option:

> update-types—use to ignore types of updates, such as semver major, minor, or patch updates on version updates (for example: version-update:semver-patch will ignore patch updates). You can combine this with dependency-name: "*" to ignore particular update-types for all dependencies. Currently, version-update:semver-major, version-update:semver-minor, and version-update:semver-patch are the only supported options. **Security updates are unaffected by this setting.**

However, in following paragraph, there is a conflicting statement that says:

> "Setting this option **will also affect pull requests for security updates** to the manifest files of this package manager, unless you use target-branch to check for version updates on a non-default branch."

For example, if I have a config file like this:
```yml
version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      # for all dependencies, only get updates for major version upgrades.
      - dependency-name: "*" 
      update-types: ["version-update:semver-patch", "version-update:semver-minor"]
```

Will dependabot ignore a security vulnerability fixed in a minor version of a direct dependency and alert the repository? The language around the `ignore` option should be updated to reflect if it applies to BOTH security and version updates, or only one of them. 

Thank you!
