### ISSUE TITLE
Variables environment variable example is misleading

### ISSUE THREAD

**Issue by kaylareopelle** [github/docs#26653]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow

### What part(s) of the article would you like to see updated?

I would like the example within [Defining environment variables for a single workflow](https://docs.github.com/en/actions/learn-github-actions/variables#defining-environment-variables-for-a-single-workflow) to be updated to use accurate syntax. 

### Additional information

I received an "Invalid workflow file" error when I tried to use the presented syntax while running ubuntu-22.04, which I believe is ubuntu-latest. 

<img width="1241" alt="Screenshot 2023-07-12 at 12 30 38 PM" src="https://github.com/github/docs/assets/87386821/cb383e9d-0745-48d0-9a55-d4e8d0c45ed4">

I tried: 
```
$DESTINATION_REPO
"$DESTINATION_REPO"
${{ $DESTINATION_REPO }}
```

And got the same error each time. Only `${{ env.DESTINATION_REPO }}` worked.

**Comment by cmwilson21** [comment]
@kaylareopelle Thank you for opening an issue and linking it to your PR! ✨

**Comment by hubwriter** [comment]
@kaylareopelle - Thanks for raising this issue and the PR.

I'd need to see your workflow to understand why using the environment variable syntax didn't work for you. However, the workflow example you are suggesting changing does work as reproduced so I don't think we'd want to change that.

The "[Using contexts to access variable values](https://docs.github.com/en/actions/learn-github-actions/variables#using-contexts-to-access-variable-values)" documentation, that's linked to from the passage you suggest changing, explains how the parts of a workflow processed on GitHub (before the workflow is processed on the runner) and can't use runner environment variables (like `$NAME`) but instead need to use contexts (like `${{ NAME }}`. I suspect this what you were coming up against. 

I'll suggest in your PR how we could clarify the docs.

**Comment by kaylareopelle** [comment]
Thanks for your patience! This issue happened both in `with` and `run` parts of a step. The environment variables were defined at the top of the workflow like this: 

```yaml
env:
  BRANCH_NAME: ruby-config-updates
  DESTINATION_REPO: kaylareopelle/docs-website
```

Here's an example using the "with" key:
```yaml
      - name: Checkout docs website repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.DESTINATION_REPO }} 
          token: ${{ secrets.KAYLA_CONFIG_DOCS }} 
```

The `repository: ${{ env.DESTINATION_REPO }}` code is where I tried the syntaxes:
* `$DESTINATION_REPO`
* `"$DESTINATION_REPO"`
* `${{ $DESTINATION_REPO }}`

I could only get the `env.` version to work. 

The same is true of the `BRANCH_NAME` variable in the following `run` command:
```yaml
      - name: Build delete command
        run: echo "delete_file=git push origin --delete ${{ env.BRANCH_NAME }} --force" >> $GITHUB_ENV
```

Here's the full job for that one: 

```yaml
  delete_branch_on_fail:
    name: Delete branch on fail
    needs: [regenerate_config_docs]
    runs-on: ubuntu-22.04
    if: failure()
    steps:
      - name: Checkout agent repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # tag v3.5.0
      - name: Checkout docs website repository
        uses: actions/checkout@v3
        with:
          repository: $DESTINATION_REPO
          token: ${{ secrets.KAYLA_CONFIG_DOCS }}

      - name: Build delete command
        run: echo "delete_file=git push origin --delete $BRANCH_NAME --force" >> $GITHUB_ENV
```

Could you help me understand why this usage is different from the example?

**Comment by hubwriter** [comment]
@kaylareopelle - Thanks for the extra details.

I'm not an expert on this, so I've asked for someone from our Actions channel to take a look at this for you.

**Comment by kaylareopelle** [comment]
Thank you!

**Comment by joshmgross** [comment]
👋 Hey @kaylareopelle,

I agree the docs are misleading here - the `$VARIABLE_NAME` syntax will *only* work in code executed by a bash shell (i.e. a `run` step on a Linux or macOS runner). It won't work on a Windows runner (which needs to use the Powershell syntax `$env:VARIABLE_NAME`) or other parts of a workflow.

In all other parts of a workflow, you'll want to use the Actions expression block `${{ }}` and the `env` context directly.

I would expect `run: echo "delete_file=git push origin --delete $BRANCH_NAME --force" >> $GITHUB_ENV` to work though. The example in the docs does work as is, it just doesn't show how to use `env` variables outside of a bash shell.

```yaml
name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
```
https://github.com/joshmgross/actions-testing/actions/runs/5788433947/job/15687418090
