### ISSUE TITLE
Form schema allows undocumented required field on checkbox options

### ISSUE THREAD

**Issue by rnowling-memphis** [github/docs#27122]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

[GitHub Form Syntax](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

### What part(s) of the article would you like to see updated?

The description of the options array for the checkboxes element only lists "label" as a valid key in the map.  But the example shows that the "required" key can also be provided:

```yaml
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: The Code of Conduct helps create a safe space for everyone. We require
      that everyone agrees to it.
    options:
      - label: I agree to follow this project's [Code of Conduct](link/to/coc)
        required: true
```

The table should be updated to list the "required" key.
