### ISSUE TITLE
Clarify case-(in)sensitivity for `matrix.<keys>`

### ISSUE THREAD

**Issue by jsoref** [github/docs#27200]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
https://docs.github.com/en/actions/learn-github-actions/contexts#matrix-context

### What part(s) of the article would you like to see updated?

Add an indication whether or not matrix elements are case sensitive.

### Additional information

Some sections indicate if items are case sensitive / case insensitive.

Developers of one project w/ which I have some affiliation were asking whether `matrix.<key>` would be case sensitive.

Here's a subset of the workflow they had:

```yaml
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
        include:
          - arch: amd64
            CC: x86_64-linux-gnu
          - arch: arm64
            CC: aarch64-linux-gnu
    runs-on: ubuntu-22.04
    env:
      AR: ${{ matrix.CC }}-ar
      CHOST: ${{ matrix.cc }}
      CC: ${{ matrix.cc }}-gcc
      CPP: ${{ matrix.cc }}-cpp
      CXX: ${{ matrix.cc }}-g++
```
