### ISSUE TITLE
DOCS: Examples of `groups` parameter for Dependabot updates has wrong indentation level

### ISSUE THREAD

**Issue by connortann** [github/docs#27987]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

### What part(s) of the article would you like to see updated?

The docs currently contain an example of using the `groups` parameter. I think it has the wrong level of indentation: the `groups` key should be under `updates`, not at the top level of the YAML config.

Here's the current example, which I think is wrong:
```
# `dependabot.yml` file using the `update-types` option to group updates.
# Any packages matching the pattern @angular* where the highest resolvable
# version is minor or patch will be grouped together.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
groups:
  angular:
    patterns:
    - "@angular*"
    update-types:
    - "minor"
    - "patch"
```

This would lead to an error like:

```
The property '#/' contains additional properties ["groups"] outside of the schema when none are allowed
```
