### ISSUE TITLE
fix github-action dependabot directory

### ISSUE THREAD

**Issue by KonradHoeffner** [github/docs#28102]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

According to <https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions>, workflow files must always be stored in `.github/workflows`. Thus the directory for dependabot should be adjusted accordingly.

The current way this is written is confusing:

```yaml
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
```

```yaml
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
```

If this is indeed correct as it is, please explain why.
