### ISSUE TITLE
Fix "Events that trigger workflows" example 

### ISSUE THREAD

**Issue by cjfryer** [github/docs#28302]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved

### What part(s) of the article would you like to see updated?

There is some example code which is incorrect:

```
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    if: github.event.review.state == 'approved' # This won't work.  The value is "APPROVED"
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was approved"
```

The docs for [`PullReviewRequestState`](https://docs.github.com/en/graphql/reference/enums#pullrequestreviewstate) in GraphQL API say these will all be upper case
