### ISSUE TITLE
Secrets example syntax is being stripped out of documentation page "Managing Complex Workflows"

### ISSUE THREAD

**Issue by nertzy** [github/docs#287]
### What is the current behavior?

Visit https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows and look at the first code example. It looks like:

```yml
jobs:
  example-job:
    steps:
      - name: Retrieve secret
        env:
          super_secret: $
        run: |
          example-command "$SUPER_SECRET"
```

But if you look at the [original markdown source](https://github.com/github/docs/blob/e666d059f91c18458c801f4fe78c42f0cdb36653/content/actions/learn-github-actions/managing-complex-workflows.md#storing-secrets) for this doc, the interpolation of the secret is present in the example:

```yml
jobs:
  example-job:
    steps:
      - name: Retrieve secret
        env:
          super_secret: ${{ secrets.SUPERSECRET }}
        run: |
          example-command "$SUPER_SECRET"
```

### What changes are you suggesting?

Clearly, this part of the YML is getting stripped out at some point in the documentation generation process. It should be fixed so that the documentation is correct.
