### ISSUE TITLE
In the page on expressions give a tangible example for contains()

### ISSUE THREAD

**Issue by david-thrower** [github/docs#29164]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/expressions

### What part(s) of the article would you like to see updated?

The section on the function contains()

### Additional information

- In this page, please consider providing a full block of code having enough context to understand accepted usage of the function contains():
- Usage is ambiguous, as it is unclear whether it should be used within ${{}} or outside thereof, otherwise where in an action it is legal to use.

- Example:

## This gets rejected without feedback

```
...
- env:
  - IS_PROD: ${{ contains(github.ref, "main") }} 
# ...
  - run:
    - echo $IS_PROD
...
```

## This prints out: 'contains(refs/heads/my_branch, "main")'  ... I expected it to print out [true | false]

```
...  
- env:
  - IS_PROD: contains(${{github.ref}}, "main")  
# ...
  - run:
    - echo $IS_PROD 
...
``` 

## Anything like this is also seems to get rejected without feedback:

```
...
  - run
    if ${{ contains(github.ref, "main") }};
    then
      echo "you are in production"
    else
      echo "You are NOT in production."
    fi
...
```
