### ISSUE TITLE
use `gh issue create` or `actions/github-script` instead of third-party action for "Scheduling issue creation" example

### ISSUE THREAD

**Issue by jcbhmr** [github/docs#29566]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

### What part(s) of the article would you like to see updated?

make it so that it uses a first-party action or tool. related to idea from #29419

ideas:

```yml
name: Weekly Team Sync
on:
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: actions/github-script@v6
        with:
          script: |
            await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Team sync",
              assignees: ["monalisa", "doctocat", "hubot"],
              labels: ["weekly sync", "docs-team"],
              body: `### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)`,
            });
```
or

```yml
name: Weekly Team Sync
on:
  schedule:
    - cron: 20 07 * * 1

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        run: |
          gh issue create \
            --repo "$REPO" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ASSIGNEES: monalisa,doctocat,hubot
          LABELS: weekly sync,docs-team
          BODY: |
            ### Agenda

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording

            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
```

### Additional information

the following pages use actions/github-script:
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/removing-a-label-when-a-card-is-added-to-a-project-board-column
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues

or this one which uses gh cli:
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

🤷‍♀️ doesnt matter which but itd be good to nail down which is preferred for docs cohesiveness and consistency.

this same "use a first-party tool" idea could also apply to https://docs.github.com/en/actions/managing-issues-and-pull-requests/moving-assigned-issues-on-project-boards

[maintainer edit]
### Content plan
Check the comment [here](https://github.com/github/docs/issues/29566#issuecomment-1789723131)
