### ISSUE TITLE
Misleading context availability on 'on.workflow_call.inputs.<inputs_id>.default'

### ISSUE THREAD

**Issue by thiagoalmeidasa** [github/docs#29812]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability

### What part(s) of the article would you like to see updated?

On https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability , is stated that we can use the `inputs` context when evaluating `default` values of another `input`.

Workflow key | Context | Special functions
-- | -- | --
on.workflow_call.inputs.<inputs_id>.default | github, inputs, vars | None

We tried to define it here https://github.com/n8n-io/n8n/blob/master/.github/workflows/e2e-reusable.yml#L28

```yaml
      cache-key:
        description: 'Cache key for modules and build artifacts.'
        required: false
        default: ${{ github.sha }}-${{ inputs.run-env }}-e2e-modules
        type: string
```

But it ignores the `${{ inputs.run-env }}` part, as you can see here: https://github.com/n8n-io/n8n/actions/runs/6765793705/job/18385947360#step:1:40

```yaml
    run-env: browsers:node18.12.0-chrome107
    cache-key: b11c4de0392289ff1ac4c4293ff92ba3bdeecbc0--e2e-modules
```

Just need to understand if it should work or not.

### Additional information

> Are you able to reliably reproduce the problem? How often does it occur? How many users are affected?

Yes, I was able to reproduce it on each and every run of my jobs. All users in Github Actions.
