### ISSUE TITLE
How to test for a specific user? Docs are very challenging to use.

### ISSUE THREAD

**Issue by guardrex** [github/docs#31165]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

I need to test if ***I am the one*** who has been assigned to an issue in order to then apply my script. The YML should in theory go something like this ...

```yml

name: Issue processing
on:
  issues:
    types:
      - assigned
jobs:
  process-blazor-issue:
    if: <<CONDITIONAL CHECK HERE>>
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### 🎉🥳 ***Happy New Year!*** 💃🕺

            A green dinosaur 🦖 will be along shortly to assist. *Stand-by ........*`
            })
            await github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["Blazor"]
            })
            await github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ["guardrex"]
            })
            await github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: [":watch: Not Triaged"]
            })
```

... and where you see `<<CONDITIONAL CHECK HERE>>`, I need a test like ...

**if the assignees contains 'guardrex'**

So ... my question is how to phrase that `if:` conditional to make this run when I'm the assigned user?

### What part(s) of the article would you like to see updated?

Your docs are very challenging to use because you don't have nearly enough examples for basic use cases. Making matters much worse, you don't have API-style docs for what's available in objects like `github.event` so that a dev can drill down into the API and see what objects they might be able to test in an `if:` conditional. It's very frustrating to use your docs for many basic use cases.
