### ISSUE TITLE
explain that even though empty should be a good way to trigger the default, it doesn't

### ISSUE THREAD

**Issue by jsoref** [github/docs#31513]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_iddefault

### What part(s) of the article would you like to see updated?

[inputs.<input_id>.default](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_iddefault)

> Optional A string representing the default value. The default value is used when an input parameter isn't specified in a workflow file.

---

This documentation isn't technically wrong. It's just an incredibly unfortunate implementation behavior because if someone uses `${{ vars.something }}` or `${{ secrets.something }}` and something _isn't_ defined in a repository (especially a fork -- this is [a thing that happens in github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) then the workflow/action will not behave as a reasonable person would expect.

> [!WARNING]
> An input that is evaluated to empty will be treated as present and suppress your default.
>
> Anyone writing a workflow that relies on an input's default should take special care to consider cases where the values they're passing will not be present.
>
> This especially includes `${{ vars.VARIABLE_NAME }}` which are unlikely to be present when run in forks and `${{ secrets.SECRET_NAME }}` which will generally not be present when run in a pull request from a fork.

### Additional information

consider this workflow: https://github.com/check-spelling-sandbox/action-default-0/actions/runs/7821238024/workflow

https://github.com/check-spelling-sandbox/action-default-0/blame/8359a59cf30619d5cb0ecf3e2dbaeb475d8b30e6/.github/workflows/blank.yml#L12-L23

```yml
name: test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test with default
        uses: ./

      - name: test with value
        uses: ./
        with:
          test: 10

      - name: test with possibly no value
        uses: ./
        with:
          test: "${{ vars.something }}"
```

https://github.com/check-spelling-sandbox/action-default-0/actions/runs/7821238024#summary-21337735816
```
test: [2]
test: [10]
test: []
```
