### ISSUE TITLE
My reusable workflow is never found by the parent workflow

### ISSUE THREAD

**Issue by nguyenalex836** [github/docs#31628]
### Discussed in https://github.com/github/docs/discussions/18381

<div type='discussions-op-text'>

<sup>Originally posted by **scottdickerson** June  1, 2022</sup>
I've been following the reusable workflows documentation here: https://docs.github.com/en/actions/using-workflows/reusing-workflows and have written a parent and child workflow

Parent workflow:
```
name: Test notify slack workflow

on: workflow_dispatch

jobs:
  NotifySlack:
      runs-on: ubuntu-20.04
      steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - uses: ./.github/workflows/notify-slack.yaml
        with:
          secrets: inherit
```

The child workflow is in a file called `./.github/workflows/notify-slack.yaml`
![image](https://user-images.githubusercontent.com/6663002/171489808-442c296e-209c-4c6f-a0f6-1cb13dcccf9b.png)

However, when the parent workflow is executed from github actions it throws this error (as if it were trying to use a reusable action)

```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/skeletor/skeletor/.github/workflows/notify-slack.yaml'. Did you forget to run actions/checkout before running your local action?
```

This is not a local action but a local reusable workflow.</div>

Comments ----------------------------------------------------------------------------------------------------

[scottdickerson](https://github.com/scottdickerson)
[on Jun 1, 2022](https://github.com/github/docs/discussions/18381#discussioncomment-2866753)
Author
Ah sorry I misread the documentation, the reused workflow has to be it's own Job to execute as a child workflow and cannot be a step within an existing job

3 replies
scottdickerson
scottdickerson
on Jun 1, 2022
Author
NotifySlack:
    needs: Publish
    uses: ./.github/workflows/notify-slack.yaml
    secrets:
      my_secret: ${{ secrets.my_secret }}
Harvz84
[Harvz84](https://github.com/Harvz84)
[on May 26, 2023](https://github.com/github/docs/discussions/18381#discussioncomment-6013243)
Thanks 👍
