### ISSUE TITLE
[GitHub Actions] GITHUB_STEP_SUMMARY is broken (sequencing issues)

### ISSUE THREAD

**Issue by iamazeem** [github/docs#31820]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions

### What part(s) of the article would you like to see updated?

- Powershell: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=powershell#adding-a-job-summary
- Bash: https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions?tool=bash#adding-a-job-summary

### Additional information

Seems like the functionality to add job step summary is broken.
The summary seems to be not honoring the sequence it was updated.

Here's a [sample workflow](https://github.com/iamazeem/test/actions/workflows/ci-win-step-summary.yml) for Windows (Powershell + Bash), Ubuntu (Bash), and macOS (Bash):

```yaml
name: win_step_summary

on: workflow_dispatch

jobs:
  win-add-content:
      runs-on: windows-latest
      steps:
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "# Heading"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  1"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  2"
      - run: Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value "- Item  3"

  win-out-file:
    runs-on: windows-latest
    steps:
    - run: '"# Heading" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  1" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  2" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'
    - run: '"- Item  3" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append'

  win-bash:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"

  ubuntu-bash:
    runs-on: ubuntu-latest
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"

  macos-bash:
    runs-on: macos-latest
    steps:
    - run: echo "# Heading" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  1" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  2" >> "$GITHUB_STEP_SUMMARY"
    - run: echo "- Item  3" >> "$GITHUB_STEP_SUMMARY"
```

Here's the output (GIF) with two attemps:

![gha-step-summary-sequence-issue](https://github.com/github/docs/assets/7128328/333927d5-59c6-45a1-beb4-466da7d3767c)
