### ISSUE TITLE
Publishing Docker images page contains broken YML code

### ISSUE THREAD

**Issue by snorremd** [github/docs#33794]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

All articles using the `{% data reusables.actions.artifact-attestations-step-for-container-images %}` template.
For example: https://github.com/github/docs/blob/main/content/actions/publishing-packages/publishing-docker-images.md

Specifically the problem is that the attestations-step-for-container-images is using an asterisk `*` instead of a dash `-` in the example.

Now it looks like this:
```yaml
      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      
      * name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
```

This can be confusing as one could believe the asterisk is some kind of special case.

### What changes are you suggesting?

Change the https://github.com/github/docs/blob/main/data/reusables/actions/artifact-attestations-step-for-container-images.md file to use a `-` so the GitHub Actions examples using attestation step are not broken.

This also requires changing the setup so the linter does not complain. See my attempts at fixing this in closed PR: https://github.com/github/docs/pull/33793
