### ISSUE TITLE
Description of vars usage is not acurate

### ISSUE THREAD

**Issue by withakay** [github/docs#34037]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/learn-github-actions/contexts#example-usage-of-the-vars-context

### What part(s) of the article would you like to see updated?

The article states "This example workflow shows how configuration variables set at the repository, environment, or organization levels are automatically available using the vars context." 

This is not acurate. In the below example where `vars.RUNNER` is a variable defined in the environment `dev` (that is to say _not_ at the repository or organisation level) then `vars.RUNNER` will not be evaluated and you can expect an error like:

`Error when evaluating 'runs-on' for job 'test-job'. .github/workflows/test-job.yaml (Line: 26, Col: 14): Unexpected value ''`

```
  test-job:
    name: "Can echo Hello World!"
    environment: "dev"
    runs-on: ${{vars.RUNNER}}
    steps:
      - name: hello-world
        run: echo "Hello World!"
```

It seems to me either the article is incorrect or there is a bug in the github actions engine as the described behaviour is not accurate.

### Additional information

**_Note this is a duplicate of the issue [here](https://github.com/github/docs/issues/333890) which was closed due to a failure to reproduce._** 

I am still able to reproduce this issue and have created a repository to demonstrate this here: **https://github.com/withakay/runner-env-var-repro**

Perhaps the tester made a mistake when configuring the repository? 🤷‍♂️

### To reproduce 

I will outline the steps to reproduce manually, but I would advise forking the [reproduction repository](https://github.com/withakay/runner-env-var-repro) and then skipping to step 2

1. create a new workflow

```
name: "Runner var test"
on:
  workflow_dispatch:

jobs:
  hello-world-job:
    name: "Can echo Hello World!"
    environment: "dev"
    runs-on: ${{vars.RUNNER}}
    steps:
      - name: hello-world
        run: echo "Hello World!"
```

2. Create an environment in the repository called 'dev'
3. Add a variable to the 'dev' environment called `RUNNER` with a value of `ubuntu-latest`
4. Run the Workflow and observe it failing in

**_It is crucial when reproducing that the RUNNER variable is added to the 'dev' environment. Adding it to a repository or organisation scoped variable will produce a false positive_**
