### ISSUE TITLE
Incorrect text in the article about Optimizing the creation of pull requests for Dependabot

### ISSUE THREAD

**Issue by erehulka** [github/docs#37136]
### Code of Conduct

- [x] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/.github/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates

### What part(s) of the article would you like to see updated?

In the mentioned [article](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates), there is an explaining text saying:
```
...Dependabot should check for version updates to npm dependencies every day at 02:00 Japanese Standard Time
```

however this is not correct, since in the following block there contains:
```yaml
schedule:
      interval: "weekly"
      day: "tuesday"
      time: "02:00"
      timezone: "Asia/Tokyo"
```

Therefore, it should be changed from _every day_ to _every Tuesday_.
