### ISSUE TITLE
Add spaces to expression in "Example returning a JSON object" section

### ISSUE THREAD

**Issue by masatakashida** [github/docs#3821]
### What article on docs.github.com is affected?

- https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

- add spaces to expression in "Example returning a JSON object" section.
  - https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-returning-a-json-object

**before**

```
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJSON(needs.job1.outputs.matrix)}}
```

**after**

```
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
```
