### ISSUE TITLE
Example of an "if" expression is not correct

### ISSUE THREAD

**Issue by adambkaplan** [github/docs#4488]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

### What part(s) of the article would you like to see updated?

The example of how to use an expression with an `if:` conditional appears to be inconsistent.
The "Contexts and expression syntax for GitHub Actions" article begins with the following:

> When you use expressions in an `if` conditional, you may omit the expression syntax (`${{ }}`) because GitHub automatically evaluates the if conditional as an expression, unless the expression contains any operators. If the expression contains any operators, the expression must be contained within `${{ }}` to explicitly mark it for evaluation. For more information about if conditionals, see "Workflow syntax for GitHub Actions."

The article then provides the following example usage:

```yaml
name: CI
on: push
jobs:
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production server on branch $GITHUB_REF"
```

The `==` symbol is an operator, and therefore requires the expression syntax.
Using this example without the expression syntax will result in the GitHub Action to fail.

### Additional information

See https://github.com/shipwright-io/build/pull/661
