### ISSUE TITLE
github actions Job status check functions - failure includes skipped

### ISSUE THREAD

**Issue by tonyhallett** [github/docs#4822]
### What is the current behavior?

[Job status check functions](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions) states 
```
failure
Returns true when any previous step of a job fails.

```
### What changes are you suggesting?

```
failure
Returns true when any previous step of a job fails or is skipped.
```

**Comment by janiceilene** [comment]
@tonyhallett Thanks for opening an issue! I'll get this triaged for the team to take a look 👀

**Comment by skedwards88** [comment]
@tonyhallett Can you share a workflow where you observe this? From my testing, if a previous step is skipped, `failure` does not return true: https://github.com/skedwards88/test-area-2/runs/2220379384?check_suite_focus=true

**Comment by tonyhallett** [comment]
Sorry, what I should have said is that failure() will evaluate to true if a dependent job is skipped.

**Comment by skedwards88** [comment]
Am I understanding correctly that what you are proposing is changing `Returns true when any previous step of a job fails` to `Returns true when any previous step of a job fails or when a dependent job is skipped`? Can you include a workflow demonstrating this?

**Comment by tonyhallett** [comment]
https://github.com/tonyhallett/DummyZipVsix/actions/runs/699438085

Look at 
```
dependent-upon-skipped:
    runs-on: windows-2019
    needs: dependent-upon-fails
    if: ${{failure()}} # there is no skipped - but this matches skipped
    steps:
      - name: needs result
        run: echo "needs result ${{needs.dependent-upon-fails.result}}"
```

![image](https://user-images.githubusercontent.com/11292998/113765306-00977c80-9714-11eb-8092-ebdb7db283bc.png)
