### ISSUE TITLE
Show API defaults where they may limit the output of an API call

### ISSUE THREAD

**Issue by cpswan** [github/docs#6517]
### What article on docs.github.com is affected?

[List labels for a repository](https://docs.github.com/en/rest/reference/issues#list-labels-for-a-repository) is where I ran into trouble, but there are probably other places.

### What part(s) of the article would you like to see updated?

The default of 30 for `per_page` isn't shown, only the max of 100.

So when repos have more than 30 labels a call to `GET /repos/{owner}/{repo}/labels` will default to only returning the first 30.

If I dive into the [REST API description](https://github.com/cpswan/rest-api-description/blob/main/descriptions/api.github.com/api.github.com.yaml) that the docs are generated from I see:

```yaml
per_page:
      name: per_page
      description: Results per page (max 100).
      in: query
      schema:
        type: integer
        default: 30
```

Name, Type, In and Description all make it to the generated table in the docs, but the default is left out.

#### Possible workaround

Change the description(s) e.g. `description: Results per page (default 30, max 100).`

### Additional information

Here's what the Parameters table looks like to me:

![image](https://user-images.githubusercontent.com/478926/118529973-071a0a80-b73c-11eb-90c0-84a70ea3166a.png)

#### Nice to have

It would also be nice if the Code samples included examples of using optional parameters like `per_page`
