### ISSUE TITLE
Document that the GitHub Actions shell examples assume what you set in run are saved to a temporary file

### ISSUE THREAD

**Issue by brettcannon** [github/docs#6554]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell

### What part(s) of the article would you like to see updated?

The table of shells gives examples of how they are used, but they are all from the perspective of passing in a file. I think clarifying that the text in the `run` key is saved to a temp file and the example command is used on that temp file would help make the examples make more sense.

### Additional information

For instance, the Python example is:
```YAML
steps:
  - name: Display the path
    run: |
      import os
      print(os.environ['PATH'])
    shell: python
```

And the shell docs say that Python uses `python {0}`. That would only work if what is specified in `run` was saved to a temp file.
