### ISSUE TITLE
GITHUB_ENV need more complete examples

### ISSUE THREAD

**Issue by jsoref** [github/docs#7892]
### What article on docs.github.com is affected?

https://docs.github.com/en/actions/reference/environment-variables#about-environment-variables makes a passing reference to `GITHUB_ENV`

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

### What part(s) of the article would you like to see updated?

All of the environment related "examples", the first one is almost an example, but even it isn't, and the rest are even less so.

```
steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> $GITHUB_ENV
  - name: Use the value
    id: step_two
    run: |
      echo "${{ env.action_state }}" # This will output 'yellow'
```

This shows using an env var via `${{ env.* }}`

It doesn't show that `${{env.*}}` won't work in the previous step (which is kinda important).

(Stylistically, it'd be nice if there was a comment in the first line of each of these example _fragments_ that pointed to code one could copy to get the rest of the boilerplate to have a working example.)

```
steps:
  - name: Set the value
    id: step_one
    run: |
      echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
      curl https://httpbin.org/json >> $GITHUB_ENV
      echo 'EOF' >> $GITHUB_ENV
```

This doesn't show that it won't be available in this step, and it doesn't show what it looks like when it's used.

```
echo "$HOME/.local/bin" >> $GITHUB_PATH
```

This is even less of an example.

A better example would use `which` or `command -v` both right after the echo, and in the next step to show the impact.

### Additional information

https://github.community/t/following-github-actions-tutorial-but-getting-an-npm-eacces-error/188088/4
