### ISSUE TITLE
Incorrect arguments in Github Actions Ruby matrix testing example

### ISSUE THREAD

**Issue by dmolesUC** [github/docs#9249]
### Code of Conduct

- [X] I have read and agree to the GitHub Docs project's [Code of Conduct](https://github.com/github/docs/blob/main/CODE_OF_CONDUCT.md)

### What article on docs.github.com is affected?

https://docs.github.com/en/actions/guides/building-and-testing-ruby#matrix-testing-your-code

### What part(s) of the article would you like to see updated?

In section "[Matrix testing your code](https://docs.github.com/en/actions/guides/building-and-testing-ruby#matrix-testing-your-code)", the sample YAML file incorrectly reads

```yml
matrix:
  os: [ubuntu, macos]
  ruby: [ … ]
```

when it should read

```yml
matrix:
  os: [ubuntu, macos]
  ruby-version: [ … ]
```

-- that is, 

<pre>ruby<strong>-version</strong>:</pre>

rather than

<pre>ruby:</pre>

### Additional information

See https://github.com/ruby/setup-ruby/issues/212

**Comment by eregon** [comment]
Actually the docs seem correct to me, on that page I see:
```yml
name: Matrix Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
        ruby: [2.5, 2.6, 2.7, head, debug, jruby, jruby-head, truffleruby, truffleruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
```
i.e. `ruby` in matrix and `${{ matrix.ruby }}` below, it's correct.
